export default function TermsPage() {
  return (
    <div className="min-h-screen bg-slate-100">

      {/* NAVBAR */}
      <div className="bg-white border-b">
        <div className="max-w-6xl mx-auto px-6 py-4 flex items-center justify-between">
          <div className="font-bold text-lg">Fish Processing Calculator</div>
          <div className="flex gap-4 text-sm">
            <a href="/" className="hover:underline">Home</a>
            <a href="/privacy" className="hover:underline">Privacy</a>
            <a href="/terms" className="hover:underline">Terms</a>
            <a href="/disclaimer" className="hover:underline">Disclaimer</a>
			<a href="/contact" className="hover:underline">Contact</a>
          </div>
        </div>
      </div>

      {/* CONTENT */}
      <div className="max-w-4xl mx-auto px-6 py-12">
        <div className="bg-white rounded-2xl border border-slate-200 p-8 shadow-sm">
          <h1 className="text-3xl font-bold mb-6">Terms & Conditions</h1>

          <div className="space-y-4 text-slate-700 leading-7">
            <p>
              The Fish Processing Calculator is provided as a tool for estimating yields, costs, labour, and profitability in fish processing operations.
            </p>

            <p>
              While every effort is made to ensure the calculations are useful and reasonable, no guarantees are made regarding accuracy, completeness, or suitability for your specific business.
            </p>

            <p>
              All results generated by this tool should be considered estimates only. Real-world outcomes may vary depending on fish quality, processing efficiency, labour conditions, and market pricing.
            </p>

            <p>
              You are responsible for reviewing and verifying all figures before making any financial, operational, or commercial decisions.
            </p>

            <p>
              Use of this website and tool is entirely at your own risk.
            </p>

            <p>
              These terms may be updated or changed at any time without notice.
            </p>
          </div>

          {/* RETURN BUTTON */}
          <div className="mt-8">
            <a
              href="/"
              className="inline-block rounded bg-slate-900 px-4 py-2 text-white text-sm hover:bg-slate-700"
            >
              ← Back to Calculator
            </a>
          </div>
        </div>
      </div>

      {/* FOOTER */}
      <div className="bg-white border-t mt-10">
        <div className="max-w-6xl mx-auto px-6 py-6 text-center text-sm text-slate-500">
          © {new Date().getFullYear()} Fish Processing Calculator. All rights reserved.
        </div>
      </div>

    </div>
  );
}